# Generated by Django 5.1.6 on 2025-03-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagerApp', '0002_alter_worker_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='projects', to='taskmanagerApp.team'),
        ),
    ]
