# Generated by Django 5.1.6 on 2025-03-11 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagerApp', '0004_remove_project_tasks_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='taskmanagerApp.project'),
        ),
    ]
