# Generated by Django 5.1.6 on 2025-03-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagerApp', '0005_alter_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='team',
            new_name='teams',
        ),
    ]
